# Generated by Django 3.1.6 on 2021-03-25 18:02

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210308_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_DSGVO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_DSGVO_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='form_of_address',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Family', 'Family'), ('Company', 'Company')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_affix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_data_colleague',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_data_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_data_successor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='use_contact_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
